services:
  - type: web
    name: ecotwin
    env: python
    plan: free
    region: oregon
    rootDir: earthday-ecotwin
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-1.5-flash
